### ISSUE TITLE
Device support error 

### ISSUE THREAD

**Issue by emagutu** [ssinyagin/rancid-ssi#1]
Hi,

I am trying to configure backups for my Huawei devices and getting the following error 

exec(hurancid) failed router manufacturer huawei: No such file or directory
exec(hurancid) failed router manufacturer huawei: No such file or directory
=====================================

Version as below 

rancid 
rancid 3.6.2

expect 
expect version 5.45

OS
DISTRIB_ID=UbuntuDISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

I followed the below instructions 

http://jira.observium.org/browse/OBSERVIUM-2020

Any pointers on how I can get this to work would be appreciated. 

Regards,
Eric Magutu

**Comment by ssinyagin** [comment]
I'm not supporting this tool, it's placed here as-is
