### ISSUE TITLE
Error: can't read "va": no such variable

### ISSUE THREAD

**Issue by Seethaar** [ssinyagin/rancid-ssi#2]
Hi there,

I run into errors, which I am trying to debug. I manually copied the contents of hulogin on to my rancid directory as that did not come as a part of Rancid 3.3

 /usr/lib/rancid/bin/hulogin -t 90 -c "display curr" 10.1.10.10

It throws the above error.

Rancid version: 3.3.0
Expect version: 5.45
Perl version: 5.22.1

I would appreciate your assistance on this.

Thanks,
AR

**Comment by ssinyagin** [comment]
hi, I'm not maintaining or supporting this tool, so you have to figure out yourself. I just made some additions about a decade ago. I have my own project "Gerty" which is replacing Rancid: https://github.com/ssinyagin/gerty

**Comment by Seethaar** [comment]
Sorry Stan,

I did not mean to open this issue at all.Did by mistake. I figured that was a PEBKAC.
Thanks for your prompt response though.


________________________________
